# Assignment 1

## Number 1

Give 3 real-world examples each of supervised and unsupervised learning, different from those discussed in the lecture notes. Clearly explain why each example falls into its respective category, highlighting the key distinction between labeled and unlabeled data in their application.

1. Supervised Learning:
   
   a. Regression:
   - Employee performance prediction: Based on several input features such as training, working quality, hours of working on a person relate to his/her career, it can predict his/her performance.
   - Impact of a particular language in a country: Based on some data, for example, number of people using that language, rating, it can calculate and then predict the outcome which is language impactation in a nation.
   - Estimate soccer league: By using various data such as number of win, lose or draw matches, total goals, assists, it can estimate the result of the league.
   
   b. Classification:
   - Animal recognition: By using some pictures which have label for the target data, the learning model can process and detect many type of animals.
   - Ethnical classification: With characteristics of human appearance, it can classify for each group of ethics which has been labelled.
   - Match result prediction: By using some data such as history dual, performance in lastest matches, it can predict a team with one of three categories: win, lost or draw.
     

2. Unsupervised Learning
   a. Clustering:
   - Music type classification: Based on some details such as frequency, pitch, amplitude, the model should try to define those to be some unknown groups.
   - Vehicle detection: With the size, number of tries in each type of vehicle or somethings else, it will find the output data without label and divide those to several groups for detecting if there are new data provided.
   - Recommendation system in social media: Based on user preferences when search or surfing on social media, the system will show more information that users mostly observe.
   




## Number 2

### Part 1

In [647]:
import numpy as np
import pandas as pd

In [648]:
A = np.array([[1,2,3],
             [1,0,1],
             [4,1,2],
             [2,3,0],
             [5,2,4],
             [0,2,5]])
A.shape

(6, 3)

In [649]:
B = np.array([[2,1,2],
              [1,3,0],
              [2,0,5]])
B.shape

(3, 3)

In [650]:
column_1 = ['Action','Drama','Documentary']
df1 = pd.DataFrame(data=A,columns=column_1)
df1

Action  Drama  Documentary
0       1      2            3
1       1      0            1
2       4      1            2
3       2      3            0
4       5      2            4
5       0      2            5

In [651]:
column_2 = ['The Batman','Mickey 17','Bowling for Columbine']
df2 = pd.DataFrame(data=B,columns=column_2)
df2

The Batman  Mickey 17  Bowling for Columbine
0           2          1                      2
1           1          3                      0
2           2          0                      5

### Part 2

In [801]:
def matrix_multi(a,b):
    try:
        result = a @ b
        print('rows x columns',result.shape)
        return result
    except:
        print("Incompatible")    

In [803]:
pos_1 = matrix_multi(A,A)

Incompatible


In [805]:
pos_2 = matrix_multi(A,A.transpose())
pos_2

rows x columns (6, 6)


array([[14,  4, 12,  8, 21, 19],
       [ 4,  2,  6,  2,  9,  5],
       [12,  6, 21, 11, 30, 12],
       [ 8,  2, 11, 13, 16,  6],
       [21,  9, 30, 16, 45, 24],
       [19,  5, 12,  6, 24, 29]])

In [807]:
pos_3 = matrix_multi(A.transpose(),A)
pos_3

rows x columns (3, 3)


array([[47, 22, 32],
       [22, 22, 26],
       [32, 26, 55]])

In [809]:
pos_4 = matrix_multi(A.transpose(),A.transpose())
pos_4

Incompatible


In [811]:
pos_5 = matrix_multi(B,B)
pos_5

rows x columns (3, 3)


array([[ 9,  5, 14],
       [ 5, 10,  2],
       [14,  2, 29]])

In [813]:
pos_6 = matrix_multi(B,B.transpose())
pos_6

rows x columns (3, 3)


array([[ 9,  5, 14],
       [ 5, 10,  2],
       [14,  2, 29]])

In [815]:
pos_7 = matrix_multi(B.transpose(),B)
pos_7

rows x columns (3, 3)


array([[ 9,  5, 14],
       [ 5, 10,  2],
       [14,  2, 29]])

In [817]:
pos_8 = matrix_multi(B.transpose(),B.transpose())
pos_8

rows x columns (3, 3)


array([[ 9,  5, 14],
       [ 5, 10,  2],
       [14,  2, 29]])

In [819]:
pos_9 = matrix_multi(A,B)
pos_9

rows x columns (6, 3)


array([[10,  7, 17],
       [ 4,  1,  7],
       [13,  7, 18],
       [ 7, 11,  4],
       [20, 11, 30],
       [12,  6, 25]])

In [821]:
pos_10 = matrix_multi(B,A)
pos_10

Incompatible


In [823]:
pos_11 = matrix_multi(B.transpose(),A)
pos_11

Incompatible


In [825]:
pos_12 = matrix_multi(A,B.transpose())
pos_12

rows x columns (6, 3)


array([[10,  7, 17],
       [ 4,  1,  7],
       [13,  7, 18],
       [ 7, 11,  4],
       [20, 11, 30],
       [12,  6, 25]])

In [827]:
pos_13 = matrix_multi(A.transpose(),B)
pos_13

Incompatible


In [829]:
pos_14 = matrix_multi(B,A.transpose())
pos_14

rows x columns (3, 6)


array([[10,  4, 13,  7, 20, 12],
       [ 7,  1,  7, 11, 11,  6],
       [17,  7, 18,  4, 30, 25]])

In [831]:
pos_15 = matrix_multi(B.transpose(),A.transpose())
pos_15

rows x columns (3, 6)


array([[10,  4, 13,  7, 20, 12],
       [ 7,  1,  7, 11, 11,  6],
       [17,  7, 18,  4, 30, 25]])

In [833]:
pos_16 = matrix_multi(A.transpose(),B.transpose())
pos_16

Incompatible


In [911]:
def dot_compare(a, b):
    if a is None or b is None:
        print("There are at least one incompatible in these matrices")
    elif np.array_equal(a, b):
        print(f"These products are equal with:\n{a}")
    else:
        print("These products aren't equal")

#### All products that has at least equal with one of the other products

In [914]:
dot_compare(pos_6,pos_5)

These products are equal with:
[[ 9  5 14]
 [ 5 10  2]
 [14  2 29]]


In [916]:
dot_compare(pos_6,pos_7)

These products are equal with:
[[ 9  5 14]
 [ 5 10  2]
 [14  2 29]]


In [918]:
dot_compare(pos_6,pos_8)

These products are equal with:
[[ 9  5 14]
 [ 5 10  2]
 [14  2 29]]


In [920]:
dot_compare(pos_5,pos_7)

These products are equal with:
[[ 9  5 14]
 [ 5 10  2]
 [14  2 29]]


In [922]:
dot_compare(pos_5,pos_8)

These products are equal with:
[[ 9  5 14]
 [ 5 10  2]
 [14  2 29]]


In [924]:
dot_compare(pos_7,pos_8)

These products are equal with:
[[ 9  5 14]
 [ 5 10  2]
 [14  2 29]]


In [926]:
dot_compare(pos_9,pos_12)

These products are equal with:
[[10  7 17]
 [ 4  1  7]
 [13  7 18]
 [ 7 11  4]
 [20 11 30]
 [12  6 25]]


In [928]:
dot_compare(pos_14,pos_15)

These products are equal with:
[[10  4 13  7 20 12]
 [ 7  1  7 11 11  6]
 [17  7 18  4 30 25]]


#### Additional Note

##### If not equal

In [932]:
dot_compare(pos_3,pos_15)

These products aren't equal


In [939]:
dot_compare(pos_3,pos_5)

These products aren't equal


##### If at least one is Incompatible

In [935]:
dot_compare(pos_1,pos_15)

There are at least one incompatible in these matrices
