#Assignment 2

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('senate_votes.csv')
df

Name Party State  B1  B2  B3  B4  B5  B6  B7  ...  B37  B38  B39  \
0       Akaka     D    HI  -1  -1   1   1   1  -1  -1  ...    1   -1   -1   
1   Alexander     R    TN   1   1   1   1   1   1   1  ...    1    1    1   
2      Allard     R    CO   1   1   1   1   1   1   1  ...    1    1    1   
3       Allen     R    VA   1   1   1   1   1   1   1  ...    1    1    1   
4      Baucus     D    MT  -1   1   1   1   1   1  -1  ...    1   -1    1   
..        ...   ...   ...  ..  ..  ..  ..  ..  ..  ..  ...  ...  ...  ...   
94      Thune     R    SD   1   1   1   1   1   1   1  ...    1    1    1   
95     Vitter     R    LA   1   1   1   1   1   1   1  ...    1    1    1   
96  Voinovich     R    OH   1  -1   1   1   1   1   1  ...    1    1    1   
97     Warner     R    VA   1   1   1   1   1   1   1  ...    1    1    1   
98      Wyden     D    OR  -1  -1   1   1   1  -1  -1  ...    1   -1    1   

    B40  B41  B42  B43  B44  B45  B46  
0     1   -1    1   -1    1    1   -1  
1     1    1    1    1    0    1    1  
2     1    1    1    1    1    1    1  
3     1    1    1    1    1    1    1  
4     0    1    1   -1    1    1    1  
..  ...  ...  ...  ...  ...  ...  ...  
94    1    1    1    1    1    1    1  
95    1    1    1    1    1    1    1  
96    1    1    1    1    1    1   -1  
97    1    1    1    1    1    1    1  
98    1    1    1   -1    1    1   -1  

[99 rows x 49 columns]

####Find the senator whose voting record is closest to Rhode Island senator, Lincoln Chafee

In [5]:
chafee_senator = df[df['Name']=='Chafee'].iloc[:,3:].to_numpy()[0]
chafee_senator

array([ 1, -1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  0,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  0,  1,  1,
        0,  1,  1, -1, -1,  1,  1,  1, -1,  1,  1, -1], dtype=int64)

In [6]:
df1 = df[df['Name'] != 'Chafee'].iloc[:,3:].to_numpy()
df1

array([[-1, -1,  1, ...,  1,  1, -1],
       [ 1,  1,  1, ...,  0,  1,  1],
       [ 1,  1,  1, ...,  1,  1,  1],
       ...,
       [ 1, -1,  1, ...,  1,  1, -1],
       [ 1,  1,  1, ...,  1,  1,  1],
       [-1, -1,  1, ...,  1,  1, -1]], dtype=int64)

In [7]:
from scipy.spatial.distance import cdist

def closest_cosine_distance(x, A):
    # Calculate cosine distances between x and all rows in A at once
    cosine_distances = cdist([x], A, metric='cosine')[0]

    # Find the index of the minimum distance
    min_index = np.argmin(cosine_distances)

    # Get the minimum distance and the corresponding row
    min_distance = cosine_distances[min_index]

    print("The minimum distance is:", min_distance)
    print("The corresponding row index is:", min_index)

    return min_index, min_distance


In [8]:
arr = closest_cosine_distance(chafee_senator,df1)

The minimum distance is: 0.0906742140393687
The corresponding row index is: 51


In [9]:
df1 = df[df['Name'] != 'Chafee']
closest_chafee = df1.iloc[[51]]
closest_chafee

Name Party State  B1  B2  B3  B4  B5  B6  B7  ...  B37  B38  B39  B40  \
52  Jeffords     I    VT   1  -1   1  -1   1   1  -1  ...    1   -1   -1    1   

    B41  B42  B43  B44  B45  B46  
52    0    1   -1    1    1   -1  

[1 rows x 49 columns]

In [10]:
jefford_senator = df[df['Name']=='Jeffords'].iloc[:,3:].to_numpy()[0]
jefford_senator

array([ 1, -1,  1, -1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1, -1, -1,  1,  0,  1, -1,  1,  1, -1], dtype=int64)

In [11]:
cosine_distance = cdist([chafee_senator], [jefford_senator], metric='cosine')[0, 0]
cosine_distance

0.0906742140393687

####Find the senator who disagrees most with Pennsylvania senator, Rick Santorum.



In [13]:
santorum_senator = df[df['Name']=='Santorum'].iloc[:,3:].to_numpy()[0]
santorum_senator

array([ 0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1], dtype=int64)

In [14]:
df2 = df[df['Name'] != 'Santorum'].iloc[:,3:].to_numpy()
df2

array([[-1, -1,  1, ...,  1,  1, -1],
       [ 1,  1,  1, ...,  0,  1,  1],
       [ 1,  1,  1, ...,  1,  1,  1],
       ...,
       [ 1, -1,  1, ...,  1,  1, -1],
       [ 1,  1,  1, ...,  1,  1,  1],
       [-1, -1,  1, ...,  1,  1, -1]], dtype=int64)

In [15]:
def farthest_cosine_distance(x, A):
    # Calculate cosine distances between x and all rows in A at once
    cosine_distances = cdist([x], A, metric='cosine')[0]

    # Find the index of the maximum distance
    max_index = np.argmax(cosine_distances)

    # Get the maximum distance and the corresponding row
    max_distance = cosine_distances[max_index]

    print("The maximum distance is:", max_distance)
    print("The corresponding row index is:", max_index)

    return max_index, max_distance

In [16]:
arr = farthest_cosine_distance(santorum_senator,df2)

The maximum distance is: 0.9340619526604212
The corresponding row index is: 39


In [17]:
df2 = df[df['Name'] != 'Santorum']
farthest_santorum = df2.iloc[[39]]
farthest_santorum

Name Party State  B1  B2  B3  B4  B5  B6  B7  ...  B37  B38  B39  B40  \
39  Feingold     D    WI  -1  -1   1  -1   1  -1  -1  ...    1   -1   -1    1   

    B41  B42  B43  B44  B45  B46  
39   -1    1   -1    1    1   -1  

[1 rows x 49 columns]

In [18]:
feingold_senator = df[df['Name']=='Feingold'].iloc[:,3:].to_numpy()[0]

cosine_distance = cdist([santorum_senator], [feingold_senator], metric='cosine')[0, 0]
cosine_distance

0.9340619526604212

####Choose 5 Democratic and 5 Republican (or more) senators.

In [20]:
from random import sample

republican_list  = df[df['Party']=='R'].sample(5, random_state = 42)
republican_list

Name Party State  B1  B2  B3  B4  B5  B6  B7  ...  B37  B38  B39  \
49     Inhofe     R    OK   1   1   1   1   1   1   1  ...    1    1    1   
11  Brownback     R    KS   1   1   1   1   1   1   1  ...    1    1    1   
51    Isakson     R    GA   1   1   1   1   1   1   1  ...    1    1    1   
23    Coleman     R    MN   1   1   1   1   1   1  -1  ...    1    1    1   
31     DeWine     R    OH   1   1   1   1   1   1  -1  ...    1    1    1   

    B40  B41  B42  B43  B44  B45  B46  
49    1    0   -1    1    1    1    1  
11    1    1    1    1    1    1    1  
51    1    1    1    1    1    1    1  
23    1    1    1   -1    1    1    1  
31    1    1    1   -1    1    1    1  

[5 rows x 49 columns]

In [21]:
democratic_list  = df[df['Party']=='D'].sample(5, random_state = 42)
democratic_list

Name Party State  B1  B2  B3  B4  B5  B6  B7  ...  B37  B38  B39  \
79  Rockefeller     D    WV   1   1   1   1   1  -1  -1  ...    1    1    1   
59   Lautenberg     D    NJ  -1  -1   1   1   1  -1  -1  ...    1    1   -1   
60        Leahy     D    VT  -1  -1   1   1   1  -1  -1  ...    0   -1   -1   
77         Reid     D    NV  -1  -1   1   1   1   1  -1  ...    1   -1   -1   
75        Pryor     D    AR  -1   1   1   1   1   1  -1  ...    1    1    1   

    B40  B41  B42  B43  B44  B45  B46  
79    1    1    0   -1    1    1   -1  
59    1    1    1   -1    1    1   -1  
60    1   -1    1   -1    1    1   -1  
77    1    1    1   -1    1    1   -1  
75    1    1    1   -1    1    1    1  

[5 rows x 49 columns]

####Compare Jefford's record with each of these 10 senators.

In [23]:
jeffords_senator = df[df['Name'] == 'Jeffords'].iloc[:,3:].to_numpy()[0]
jeffords_senator

array([ 1, -1,  1, -1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1, -1, -1,  1,  0,  1, -1,  1,  1, -1], dtype=int64)

In [24]:
republican_list = republican_list.iloc[:,3:].to_numpy()
democratic_list = democratic_list.iloc[:,3:].to_numpy()

In [25]:
def cosine_distance(x, A):
    # Calculate cosine distances between x and all rows in A at once
    cosine_distances = cdist([x], A, metric='cosine')[0]

    return cosine_distances

In [26]:
republican_distance = cosine_distance(jeffords_senator,republican_list)
republican_distance

array([0.66666667, 0.45051627, 0.49447497, 0.33333333, 0.31864018])

In [27]:
democratic_distance = cosine_distance(jeffords_senator,democratic_list)
democratic_distance

array([0.50502525, 0.45051627, 0.34827347, 0.31864018, 0.31864018])

Bacause mostly republican_distance > democratic_distance => Jim Jeffords near to be a Democratic